FROM node:20-alpine as builder

WORKDIR /frontend

COPY package*.json ./

RUN npm config set fetch-retry-maxtimeout 60000

RUN npm config set registry https://registry.npmjs.org/

RUN npm install -g npm@latest

RUN npm install

COPY . .

ARG GOOGLE_API_KEY

ENV GOOGLE_MAPS_API_KEY=$GOOGLE_API_KEY

RUN npm run build

RUN ls -la /frontend/.next

FROM node:20-alpine

WORKDIR /frontend

COPY --from=builder /frontend .

RUN npm install --production

EXPOSE 80

CMD ["npm", "start"]


















