# Usar uma imagem oficial do Node.js como base
FROM node:16-alpine

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar os arquivos de dependências para dentro do container
COPY package*.json ./

# Instalar as dependências no container
RUN npm install

# Copiar o restante dos arquivos da aplicação para o container
COPY . .

# Expor a porta 80 (para o frontend)
EXPOSE 80

# Rodar a aplicação Next.js
CMD ["npm", "run", "start"]
