services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "80:3000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - ./frontend/.next:/next
      - /app/node_modules
      - ./out:/app/out
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
