version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mapeia a porta 8080 do container para a porta 8080 da máquina local
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend:/app # Volume para desenvolvimento (sync de código)
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000" # Mapeia a porta 80 do container para a porta 3000 do Next.js
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./frontend:/app # Volume para desenvolvimento (sync de código)
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
