# Usar uma imagem oficial do Node.js como base
FROM node:18-buster-slim
# Instalar Python 3, build-essential e outras dependências necessárias
RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip \
  build-essential \
  && rm -rf /var/lib/apt/lists/*
# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar os arquivos de dependências para dentro do container
COPY package*.json ./

# Instalar as dependências no container
RUN npm install

# Copiar o restante dos arquivos da aplicação para o container
COPY . .

# Construir a aplicação
RUN npm run build

# Expor a porta 8080
EXPOSE 8080

# Rodar a aplicação
CMD ["npm", "run", "start"]
